name: Ideia
description: Sugestao de melhoria
title: "[Ideia] "
labels: ["ideia"]
body:
  - type: textarea
    id: problema
    attributes:
      label: Qual problema isso resolve
    validations:
      required: true
  - type: textarea
    id: proposta
    attributes:
      label: Proposta
    validations:
      required: true
